feat: add capability to plot file size chronology for valid files
noaa-psd/observation-inventory-utils pull request #9
Opened 2022-04-05 16:16 UTC by slawrence87544

body: this commit will make it possible to plot observation file
size chronology for all valid files only.

2022-04-05 17:01 UTC, frolovsa requested changes
Steve. looks good. thank you. 
General comment. It would be great to see some additional comments on why and how you are massaging the data before plotting.

2022-04-05 17:01 UTC, frolovsa commented on src/obs_inv_utils/plot_generator.py
> +        unique_rows = data.sort_values(
maybe add a comment on why there are duplicates etc.

2022-04-05 17:01 UTC, frolovsa commented on src/obs_inv_utils/plot_generator.py
> +        uf = data.sort_values(
maybe add a comment on why there are duplicates and how you filter for them

2022-04-05 17:01 UTC, frolovsa commented on src/obs_inv_utils/plot_generator.py
> +        uf['generic_fn'] = uf['prefix'] + '.tag.' + uf['un']
add a comment on why you doing this massaging. E.g. 
`# make field names used in plotting`

2022-04-06 23:06 UTC, HenryWinterbottom-NOAA commented
Looks good to me.

2022-04-06 23:06 UTC, HenryWinterbottom-NOAA approved these changes

2022-04-08 18:18 UTC, slawrence87544 commented on src/obs_inv_utils/plot_generator.py
> +        uf = data.sort_values(
Added clarifying comments.

2022-04-08 18:18 UTC, slawrence87544 commented on src/obs_inv_utils/plot_generator.py
> +        unique_rows = data.sort_values(
Removed code section as it was unnecessary.

2022-04-08 18:32 UTC, frolovsa approved these changes

2022-04-08 21:01 UTC, merged

2022-04-13 22:54 UTC, HenryWinterbottom-NOAA reviewed
These look good to me.